name: Build HMA-OSS Manager

on:
  workflow_dispatch:

env:
  # å¯é€‰ï¼šä»è¾“å…¥æˆ–é»˜è®¤å€¼è·å–
  CUSTOM_APP_NAME: ${{ github.event.inputs.app_name || 'Myhma_oss' }}
  CUSTOM_PACKAGE_NAME: ${{ github.event.inputs.package_name || 'com.example.myfork.hma_oss' }}

jobs:
  build-manager:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}   # ğŸ‘ˆ å…¨å±€å¯ç”¨ï¼
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0



      - name: Customize APK identity (package name, app name)
        run: |
          echo "Replacing package name with: $CUSTOM_PACKAGE_NAME"
          echo "Replacing app name with: $CUSTOM_APP_NAME"

          # 1. Replace package name in root build.gradle.kts
          sed -i "/^android {/a \ \ \ \ defaultConfig {\n\ \ \ \ \ \ \ \ applicationId = \"$CUSTOM_PACKAGE_NAME\"\n\ \ \ \ }" app/build.gradle.kts
          cat app/build.gradle.kts
          

          # 2. Replace app_name in all strings.xml
          find app/src/main/res/values -name "strings.xml" -exec sed -i "s|<string name=\"app_name\" translatable=\"false\">.*</string>|<string name=\"app_name\" translatable=\"false\">$CUSTOM_APP_NAME</string>|g" {} \;

          # 3. Replace android:label in AndroidManifest.xml
          sed -i "s/android:label=\"[^\"]*\"/android:label=\"$CUSTOM_APP_NAME\"/g" app/src/main/AndroidManifest.xml
         

          

      - name: Generate version
        id: parse_version
        run: |
          COMMIT_NUM=$(git rev-list --count HEAD)
          VERSION_CODE=$(echo "$COMMIT_NUM + 200 + 10000" | bc)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          VERSION_NAME="${VERSION_CODE}_${COMMIT_HASH}"
          BRANCH=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/refs\/tags\///')
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_OUTPUT
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_OUTPUT
          
          echo "Generated versionCode: $VERSION_CODE"
          echo "Generated versionName: $VERSION_NAME"

      

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Write key
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
          echo localBuild2=false >> local.properties
          echo storePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
          echo keyAlias='${{ secrets.KEY_ALIAS }}' >> local.properties
          echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> local.properties
          echo fileDir=`pwd`/key.jks >> local.properties
          
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > key.jks

      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Gradle prebuild
        run: |
          ./gradlew prebuild

      - name: Build all
        id: buildAll
        run: |
          ./gradlew assemble \
            -PmanagerVersionCode=${{ steps.parse_version.outputs.VERSION_CODE }} \
            -PmanagerVersionName=${{ steps.parse_version.outputs.VERSION_NAME }} \
            -Pbranchname=${{ steps.parse_version.outputs.BRANCH_NAME }}
          echo "releaseName=$(ls app/build/outputs/apk/release/*.apk | awk -F '(/|.apk)' '{print $6}')" >> $GITHUB_OUTPUT
          echo "debugName=$(ls app/build/outputs/apk/debug/*.apk | awk -F '(/|.apk)' '{print $6}')" >> $GITHUB_OUTPUT
          echo "releaseFile=$(ls app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT
          echo "debugFile=$(ls app/build/outputs/apk/debug/*.apk)" >> $GITHUB_OUTPUT
          echo "ossNum=$(ls app/build/outputs/apk/debug/*.apk | awk -F '(/|.apk)' '{print $6}' | cut -f4 -d'-')" >> $GITHUB_OUTPUT

      - name: Upload release
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.buildAll.outputs.releaseName }}
          path: "app/build/outputs/apk/release/*.apk"

      
